-- 1. Tabla de menus: el catalogo semanal que se publica
create table if not exists menus (
  id bigint generated by default as identity primary key,
  dia text not null,
  platillo text not null,
  descripcion text,
  calorias integer,
  created_at timestamptz default now()
);

-- 2. Tabla de reservas: los estudiantes que confirman comida
create table if not exists reservas (
  id bigint generated by default as identity primary key,
  estudiante text not null,
  documento text not null,
  sede text not null,
  turno text not null,
  fecha date not null,
  asistio boolean default false,
  created_at timestamptz default now()
);

-- Si la tabla ya existia sin la columna de asistencia, se agrega aca
alter table reservas add column if not exists asistio boolean default false;

-- 3. Tabla de contactos: mensajes del formulario de contacto
create table if not exists contactos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  correo text not null,
  mensaje text not null,
  created_at timestamptz default now()
);

-- 4. Tabla de avisos: noticias que publica el administrador
-- Se muestran en la pagina de inicio y el bot las conoce.
create table if not exists avisos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  texto text not null,
  fecha text,
  created_at timestamptz default now()
);

-- 5. Tabla de beneficiarios: registro de los estudiantes del programa
-- La reserva valida que el documento exista aqui antes de guardarse.
create table if not exists beneficiarios (
  id bigint generated by default as identity primary key,
  documento text not null unique,
  nombre text not null,
  sede text not null,
  turno text not null,
  grado text,
  created_at timestamptz default now()
);

-- 6. Tabla de valoraciones: estrellas que dan los estudiantes a los platos
create table if not exists valoraciones (
  id bigint generated by default as identity primary key,
  menu_id bigint not null references menus(id) on delete cascade,
  puntos integer not null check (puntos between 1 and 5),
  documento text,
  created_at timestamptz default now()
);

-- 7. Tabla de notificaciones: confirmaciones de reserva enviadas
create table if not exists notificaciones (
  id bigint generated by default as identity primary key,
  tipo text not null,
  destinatario text,
  mensaje text,
  enviado boolean default false,
  created_at timestamptz default now()
);

-- ============================================================
-- 4. Politicas de acceso (RLS)
-- Sin estas politicas la app no puede leer/escribir.
-- RLS activo + politicas = la app publica lee menus y guarda
-- reservas/contactos.
--
-- IMPORTANTE: antes de cada create policy se borra la que ya
-- exista ("drop policy if exists"), asi este script se puede
-- correr cuantas veces se quiera sin dar error.
-- ============================================================

alter table menus enable row level security;
drop policy if exists "menus_lectura_publica" on menus;
create policy "menus_lectura_publica" on menus
  for select using (true);
drop policy if exists "menus_escritura_admin" on menus;
create policy "menus_escritura_admin" on menus
  for insert with check (true);

alter table reservas enable row level security;
drop policy if exists "reservas_lectura" on reservas;
create policy "reservas_lectura" on reservas
  for select using (true);
drop policy if exists "reservas_creacion" on reservas;
create policy "reservas_creacion" on reservas
  for insert with check (true);
-- Permite limpiar datos de prueba desde la API (proyecto educativo)
drop policy if exists "reservas_borrado" on reservas;
create policy "reservas_borrado" on reservas
  for delete using (true);

alter table contactos enable row level security;
drop policy if exists "contactos_lectura" on contactos;
create policy "contactos_lectura" on contactos
  for select using (true);
drop policy if exists "contactos_creacion" on contactos;
create policy "contactos_creacion" on contactos
  for insert with check (true);

alter table avisos enable row level security;
drop policy if exists "avisos_lectura" on avisos;
create policy "avisos_lectura" on avisos
  for select using (true);
drop policy if exists "avisos_creacion" on avisos;
create policy "avisos_creacion" on avisos
  for insert with check (true);
drop policy if exists "avisos_borrado" on avisos;
create policy "avisos_borrado" on avisos
  for delete using (true);

alter table beneficiarios enable row level security;
drop policy if exists "beneficiarios_lectura" on beneficiarios;
create policy "beneficiarios_lectura" on beneficiarios
  for select using (true);
drop policy if exists "beneficiarios_creacion" on beneficiarios;
create policy "beneficiarios_creacion" on beneficiarios
  for insert with check (true);
drop policy if exists "beneficiarios_borrado" on beneficiarios;
create policy "beneficiarios_borrado" on beneficiarios
  for delete using (true);

alter table valoraciones enable row level security;
drop policy if exists "valoraciones_lectura" on valoraciones;
create policy "valoraciones_lectura" on valoraciones
  for select using (true);
drop policy if exists "valoraciones_creacion" on valoraciones;
create policy "valoraciones_creacion" on valoraciones
  for insert with check (true);
drop policy if exists "valoraciones_actualizacion" on valoraciones;
create policy "valoraciones_actualizacion" on valoraciones
  for update using (true);

alter table notificaciones enable row level security;
drop policy if exists "notificaciones_lectura" on notificaciones;
create policy "notificaciones_lectura" on notificaciones
  for select using (true);
drop policy if exists "notificaciones_creacion" on notificaciones;
create policy "notificaciones_creacion" on notificaciones
  for insert with check (true);

-- ============================================================
-- 5. Datos de ejemplo: menu de la semana
-- Se insertan SOLO si la tabla esta vacia (evita duplicados)
-- ============================================================
insert into menus (dia, platillo, descripcion, calorias)
select datos.dia, datos.platillo, datos.descripcion, datos.calorias
from (values
  ('Lunes', 'Arroz con pollo y ensalada', 'Arroz, pollo guisado, ensalada fresca y jugo natural.', 520),
  ('Martes', 'Sopa de verduras y pan', 'Sopa de verduras de temporada con pan integral.', 380),
  ('Miercoles', 'Pasta con salsa de tomate', 'Pasta integral con salsa casera de tomate y queso.', 460),
  ('Jueves', 'Pescado con arroz y platano', 'Pescado al horno, arroz blanco y platano asado.', 490),
  ('Viernes', 'Sancocho de gallina', 'Sancocho tradicional con yuca, platano y papa.', 550)
) as datos(dia, platillo, descripcion, calorias)
where not exists (select 1 from menus);

-- Avisos de ejemplo: solo si la tabla esta vacia
insert into avisos (titulo, texto, fecha)
select datos.titulo, datos.texto, datos.fecha
from (values
  ('Suspension del servicio', 'Viernes no habra servicio por jornada pedagogica. Las minutas se reprogramaran.', 'Permanece atento'),
  ('Reserva de minutas en linea', 'Ya puedes reservar tu comida desde la aplicacion para evitar el desperdicio.', 'Novedad'),
  ('Actualizacion de datos', 'Mantén actualizada la informacion de los estudiantes para el programa.', 'Recordatorio')
) as datos(titulo, texto, fecha)
where not exists (select 1 from avisos);

-- Beneficiarios de ejemplo: solo si la tabla esta vacia
-- Estos documentos son los que puede usar un estudiante para reservar
insert into beneficiarios (documento, nombre, sede, turno, grado)
select datos.documento, datos.nombre, datos.sede, datos.turno, datos.grado
from (values
  ('1234567890', 'Ana Maria Lopez', 'Sede A', 'Almuerzo', '5'),
  ('2345678901', 'Carlos Andres Perez', 'Sede A', 'Refrigerio', '3'),
  ('3456789012', 'Laura Valentina Gomez', 'Sede B', 'Almuerzo', '7'),
  ('4567890123', 'Sebastian Rodriguez', 'Sede B', 'Refrigerio', '9'),
  ('5678901234', 'Valentina Torres', 'Sede C', 'Almuerzo', '11'),
  ('6789012345', 'Andres Felipe Ramirez', 'Sede C', 'Refrigerio', '6'),
  ('7890123456', 'Sofia Martinez', 'Sede A', 'Almuerzo', '4'),
  ('8901234567', 'Juan Pablo Castro', 'Sede B', 'Refrigerio', '10'),
  ('9012345678', 'Mariana Suarez', 'Sede C', 'Almuerzo', '8'),
  ('0123456789', 'Daniel Vargas', 'Sede A', 'Refrigerio', '2')
) as datos(documento, nombre, sede, turno, grado)
where not exists (select 1 from beneficiarios);

-- Valoraciones de ejemplo: algunas estrellas ya puestas por los
-- estudiantes (solo si la tabla esta vacia)
insert into valoraciones (menu_id, puntos, documento)
select m.id, datos.puntos, datos.documento
from (values
  ('Arroz con pollo y ensalada', 5, '1234567890'),
  ('Arroz con pollo y ensalada', 4, '7890123456'),
  ('Sopa de verduras y pan', 3, '2345678901'),
  ('Pasta con salsa de tomate', 4, '5678901234'),
  ('Pescado con arroz y platano', 5, '3456789012'),
  ('Sancocho de gallina', 5, '9012345678'),
  ('Sancocho de gallina', 4, '4567890123')
) as datos(platillo, puntos, documento)
join menus m on m.platillo = datos.platillo
where not exists (select 1 from valoraciones);
