-- 1. Tabla de menus: el catalogo semanal que se publica
-- El PAE rota el menu por SEMANA del mes (1-4) y cada dia tiene una
-- comida DIFERENTE por jornada: una para Almuerzo y otra para Refrigerio.
-- Por eso cada fila es: semana + dia + jornada + platillo.
create table if not exists menus (
  id bigint generated by default as identity primary key,
  semana integer not null default 1,
  dia text not null,
  jornada text not null default 'Almuerzo',
  platillo text not null,
  descripcion text,
  calorias integer,
  imagen text,
  created_at timestamptz default now()
);

-- Migracion para bases que ya existian con el modelo anterior
-- (la columna "jornadas" era una lista). Se crean las columnas nuevas
-- si faltan, cada fila se queda con su primera jornada y se agrega
-- semana = 1. La columna vieja se elimina.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'menus' and column_name = 'jornadas'
  ) then
    alter table menus add column if not exists semana integer not null default 1;
    alter table menus add column if not exists jornada text not null default 'Almuerzo';
    update menus
    set jornada = case when array_length(jornadas, 1) >= 1 then jornadas[1] else 'Almuerzo' end
    where jornada is null or jornada = 'Almuerzo';
    execute 'alter table menus drop column jornadas';
  end if;
end $$;

-- 2. Tabla de reservas: los estudiantes que confirman comida
create table if not exists reservas (
  id bigint generated by default as identity primary key,
  estudiante text not null,
  documento text not null,
  sede text not null,
  turno text not null,
  fecha date not null,
  asistio boolean default false,
  created_at timestamptz default now()
);

-- Si la tabla ya existia sin la columna de asistencia, se agrega aca
alter table reservas add column if not exists asistio boolean default false;

-- 3. Tabla de contactos: mensajes del formulario de contacto
create table if not exists contactos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  correo text not null,
  mensaje text not null,
  created_at timestamptz default now()
);

-- 4. Tabla de avisos: noticias que publica el administrador
-- Se muestran en la pagina de inicio y el bot las conoce.
create table if not exists avisos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  texto text not null,
  fecha text,
  created_at timestamptz default now()
);

-- Los avisos tambien pueden llevar una imagen de referencia
alter table avisos add column if not exists imagen text;

-- 5. Tabla de beneficiarios: registro de los estudiantes del programa
-- La reserva valida que el documento exista aqui antes de guardarse.
create table if not exists beneficiarios (
  id bigint generated by default as identity primary key,
  documento text not null unique,
  nombre text not null,
  sede text not null,
  turno text not null,
  grado text,
  created_at timestamptz default now()
);

-- 6. Tabla de valoraciones: estrellas que dan los estudiantes a los platos
create table if not exists valoraciones (
  id bigint generated by default as identity primary key,
  menu_id bigint not null references menus(id) on delete cascade,
  puntos integer not null check (puntos between 1 and 5),
  documento text,
  created_at timestamptz default now()
);

-- 7. Tabla de notificaciones: confirmaciones de reserva enviadas
create table if not exists notificaciones (
  id bigint generated by default as identity primary key,
  tipo text not null,
  destinatario text,
  mensaje text,
  enviado boolean default false,
  created_at timestamptz default now()
);

-- 8. Tabla de galeria: fotos propias del programa (eventos, equipo,
-- novedades) que publica el administrador. Se muestran en la Home.
create table if not exists galeria (
  id bigint generated by default as identity primary key,
  titulo text not null,
  imagen text not null,
  created_at timestamptz default now()
);

-- 9. Tabla de instituciones: las instituciones educativas cubiertas
-- por el PAE. Su cantidad alimenta la metrica real de la Home.
create table if not exists instituciones (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamptz default now()
);

-- 10. Tabla de colaboradores: el equipo humano del PAE (cocina,
-- coordinacion, apoyo). Su cantidad alimenta la metrica real.
create table if not exists colaboradores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  rol text,
  created_at timestamptz default now()
);

-- ============================================================
-- 4. Politicas de acceso (RLS)
-- Sin estas politicas la app no puede leer/escribir.
-- RLS activo + politicas = la app publica lee menus y guarda
-- reservas/contactos.
--
-- IMPORTANTE: antes de cada create policy se borra la que ya
-- exista ("drop policy if exists"), asi este script se puede
-- correr cuantas veces se quiera sin dar error.
-- ============================================================

alter table menus enable row level security;
drop policy if exists "menus_lectura_publica" on menus;
create policy "menus_lectura_publica" on menus
  for select using (true);
drop policy if exists "menus_escritura_admin" on menus;
create policy "menus_escritura_admin" on menus
  for insert with check (true);
-- Permite al admin eliminar platos del menu desde el panel
drop policy if exists "menus_borrado_admin" on menus;
create policy "menus_borrado_admin" on menus
  for delete using (true);

alter table reservas enable row level security;
drop policy if exists "reservas_lectura" on reservas;
create policy "reservas_lectura" on reservas
  for select using (true);
drop policy if exists "reservas_creacion" on reservas;
create policy "reservas_creacion" on reservas
  for insert with check (true);
-- Permite limpiar datos de prueba desde la API (proyecto educativo)
drop policy if exists "reservas_borrado" on reservas;
create policy "reservas_borrado" on reservas
  for delete using (true);

alter table contactos enable row level security;
drop policy if exists "contactos_lectura" on contactos;
create policy "contactos_lectura" on contactos
  for select using (true);
drop policy if exists "contactos_creacion" on contactos;
create policy "contactos_creacion" on contactos
  for insert with check (true);

alter table avisos enable row level security;
drop policy if exists "avisos_lectura" on avisos;
create policy "avisos_lectura" on avisos
  for select using (true);
drop policy if exists "avisos_creacion" on avisos;
create policy "avisos_creacion" on avisos
  for insert with check (true);
drop policy if exists "avisos_borrado" on avisos;
create policy "avisos_borrado" on avisos
  for delete using (true);

alter table beneficiarios enable row level security;
drop policy if exists "beneficiarios_lectura" on beneficiarios;
create policy "beneficiarios_lectura" on beneficiarios
  for select using (true);
drop policy if exists "beneficiarios_creacion" on beneficiarios;
create policy "beneficiarios_creacion" on beneficiarios
  for insert with check (true);
drop policy if exists "beneficiarios_borrado" on beneficiarios;
create policy "beneficiarios_borrado" on beneficiarios
  for delete using (true);

alter table valoraciones enable row level security;
drop policy if exists "valoraciones_lectura" on valoraciones;
create policy "valoraciones_lectura" on valoraciones
  for select using (true);
drop policy if exists "valoraciones_creacion" on valoraciones;
create policy "valoraciones_creacion" on valoraciones
  for insert with check (true);
drop policy if exists "valoraciones_actualizacion" on valoraciones;
create policy "valoraciones_actualizacion" on valoraciones
  for update using (true);

alter table notificaciones enable row level security;
drop policy if exists "notificaciones_lectura" on notificaciones;
create policy "notificaciones_lectura" on notificaciones
  for select using (true);
drop policy if exists "notificaciones_creacion" on notificaciones;
create policy "notificaciones_creacion" on notificaciones
  for insert with check (true);

alter table galeria enable row level security;
drop policy if exists "galeria_lectura" on galeria;
create policy "galeria_lectura" on galeria
  for select using (true);
drop policy if exists "galeria_creacion" on galeria;
create policy "galeria_creacion" on galeria
  for insert with check (true);
drop policy if exists "galeria_borrado" on galeria;
create policy "galeria_borrado" on galeria
  for delete using (true);

alter table instituciones enable row level security;
drop policy if exists "instituciones_lectura" on instituciones;
create policy "instituciones_lectura" on instituciones
  for select using (true);
drop policy if exists "instituciones_creacion" on instituciones;
create policy "instituciones_creacion" on instituciones
  for insert with check (true);
drop policy if exists "instituciones_borrado" on instituciones;
create policy "instituciones_borrado" on instituciones
  for delete using (true);

alter table colaboradores enable row level security;
drop policy if exists "colaboradores_lectura" on colaboradores;
create policy "colaboradores_lectura" on colaboradores
  for select using (true);
drop policy if exists "colaboradores_creacion" on colaboradores;
create policy "colaboradores_creacion" on colaboradores
  for insert with check (true);
drop policy if exists "colaboradores_borrado" on colaboradores;
create policy "colaboradores_borrado" on colaboradores
  for delete using (true);

-- ============================================================
-- 4.1 Bucket de imagenes (Supabase Storage)
-- Aqui se guardan las fotos de las minutas y los avisos.
-- Es publico para que cualquier persona pueda verlas, y cualquiera
-- puede subir (el backend ya valida que sea el administrador).
-- ============================================================
insert into storage.buckets (id, name, public)
values ('imagenes', 'imagenes', true)
on conflict (id) do nothing;

drop policy if exists "imagenes_leer" on storage.objects;
create policy "imagenes_leer" on storage.objects
  for select using (bucket_id = 'imagenes');

drop policy if exists "imagenes_subir" on storage.objects;
create policy "imagenes_subir" on storage.objects
  for insert with check (bucket_id = 'imagenes');

drop policy if exists "imagenes_borrar" on storage.objects;
create policy "imagenes_borrar" on storage.objects
  for delete using (bucket_id = 'imagenes');

-- ============================================================
-- 5. Datos de ejemplo: menu del PAE
-- El menu rota por semana del mes (1-4) y cada dia tiene una comida
-- DIFERENTE por jornada (Almuerzo y Refrigerio). Se inserta la
-- semana 1 y 2 completa como ejemplo; las semanas 3 y 4 las puede
-- cargar el administrador desde el panel.
-- Solo se insertan si la tabla esta vacia (evita duplicados)
-- ============================================================
insert into menus (semana, dia, jornada, platillo, descripcion, calorias, imagen)
select datos.semana, datos.dia, datos.jornada, datos.platillo, datos.descripcion,
       datos.calorias, datos.imagen
from (values
  -- Semana 1
  (1, 'Lunes', 'Almuerzo', 'Arroz con pollo y ensalada', 'Arroz, pollo guisado, ensalada fresca y jugo natural.', 520, NULL),
  (1, 'Lunes', 'Refrigerio', 'Sandwich de queso y fruta', 'Sandwich integral con queso, manzana y agua.', 340, NULL),
  (1, 'Martes', 'Almuerzo', 'Sopa de verduras y pan', 'Sopa de verduras de temporada con pan integral.', 380, NULL),
  (1, 'Martes', 'Refrigerio', 'Yogurt con avena', 'Yogurt con avena y trozos de platano.', 320, NULL),
  (1, 'Miercoles', 'Almuerzo', 'Pasta con salsa de tomate', 'Pasta integral con salsa casera de tomate y queso.', 460, NULL),
  (1, 'Miercoles', 'Refrigerio', 'Empanada de carne y jugo', 'Empanada horneada de carne con jugo de naranja.', 380, NULL),
  (1, 'Jueves', 'Almuerzo', 'Pescado con arroz y platano', 'Pescado al horno, arroz blanco y platano asado.', 490, NULL),
  (1, 'Jueves', 'Refrigerio', 'Arepa con queso y chocolate', 'Arepa de maiz con queso y chocolate caliente.', 400, NULL),
  (1, 'Viernes', 'Almuerzo', 'Sancocho de gallina', 'Sancocho tradicional con yuca, platano y papa.', 550, NULL),
  (1, 'Viernes', 'Refrigerio', 'Galletas de avena y leche', 'Galletas de avena con un vaso de leche.', 300, NULL),
  -- Semana 2
  (2, 'Lunes', 'Almuerzo', 'Carne guisada con arroz', 'Carne guisada, arroz blanco, frijoles y ensalada.', 540, NULL),
  (2, 'Lunes', 'Refrigerio', 'Pan con huevo y mango', 'Pan con huevo y rodajas de mango.', 350, NULL),
  (2, 'Martes', 'Almuerzo', 'Arroz con pollo y frijol', 'Arroz con pollo, frijol caliente y platano.', 530, NULL),
  (2, 'Martes', 'Refrigerio', 'Avena con pan', 'Avena caliente con pan de yuca.', 330, NULL),
  (2, 'Miercoles', 'Almuerzo', 'Pechuga a la plancha con verdura', 'Pechuga a la plancha con verduras salteadas y arroz.', 470, NULL),
  (2, 'Miercoles', 'Refrigerio', 'Fruta con galleta', 'Porcion de fruta variada con galleta integral.', 260, NULL),
  (2, 'Jueves', 'Almuerzo', 'Cazuela de frijoles', 'Cazuela de frijoles con arroz y aguacate.', 520, NULL),
  (2, 'Jueves', 'Refrigerio', 'Bocadillo con queso y agua', 'Bocadillo de guayaba con queso y agua.', 310, NULL),
  (2, 'Viernes', 'Almuerzo', 'Sudado de pollo con arroz', 'Sudado de pollo con papas, arroz y ensalada.', 500, NULL),
  (2, 'Viernes', 'Refrigerio', 'Sorbete de frutas y galleta', 'Sorbete de frutas naturales con galleta.', 290, NULL)
) as datos(semana, dia, jornada, platillo, descripcion, calorias, imagen)
where not exists (select 1 from menus);

-- Instituciones educativas de ejemplo (metricas reales de la Home)
insert into instituciones (nombre)
select datos.nombre
from (values
  ('I.E. San Jose'),
  ('I.E. La Esperanza'),
  ('I.E. Gabriel Garcia Marquez'),
  ('I.E. Nueva Granada'),
  ('I.E. El Rosario'),
  ('I.E. Ciudadela Educativa'),
  ('I.E. Rafael Nunez')
) as datos(nombre)
where not exists (select 1 from instituciones);

-- Colaboradores del PAE de ejemplo (metricas reales de la Home)
insert into colaboradores (nombre, rol)
select datos.nombre, datos.rol
from (values
  ('Maria Fernanda Ruiz', 'Coordinadora PAE'),
  ('Jorge Andres Diaz', 'Nutricionista'),
  ('Carmen Elena Torres', 'Jefa de cocina'),
  ('Luis Alberto Castro', 'Cocinero'),
  ('Rosa Maria Suarez', 'Cocinera'),
  ('Pedro Julio Garcia', 'Cocinero'),
  ('Luisa Fernanda Mora', 'Cocinera'),
  ('Alberto Jose Rincon', 'Manipulador de alimentos'),
  ('Diana Carolina Ortiz', 'Manipuladora de alimentos'),
  ('Hernan Dario Medina', 'Auxiliar de servicios'),
  ('Paola Andrea Vega', 'Auxiliar de servicios'),
  ('Ricardo Andres Leon', 'Apoyo logistico'),
  ('Gloria Esperanza Pardo', 'Apoyo logistico'),
  ('Sandra Milena Bonilla', 'Auxiliar administrativo')
) as datos(nombre, rol)
where not exists (select 1 from colaboradores);

-- Avisos de ejemplo: solo si la tabla esta vacia
insert into avisos (titulo, texto, fecha)
select datos.titulo, datos.texto, datos.fecha
from (values
  ('Suspension del servicio', 'Viernes no habra servicio por jornada pedagogica. Las minutas se reprogramaran.', 'Permanece atento'),
  ('Reserva de minutas en linea', 'Ya puedes reservar tu comida desde la aplicacion para evitar el desperdicio.', 'Novedad'),
  ('Actualizacion de datos', 'Mantén actualizada la informacion de los estudiantes para el programa.', 'Recordatorio')
) as datos(titulo, texto, fecha)
where not exists (select 1 from avisos);

-- Beneficiarios de ejemplo: solo si la tabla esta vacia
-- Estos documentos son los que puede usar un estudiante para reservar
insert into beneficiarios (documento, nombre, sede, turno, grado)
select datos.documento, datos.nombre, datos.sede, datos.turno, datos.grado
from (values
  ('1234567890', 'Ana Maria Lopez', 'Sede A', 'Almuerzo', '5'),
  ('2345678901', 'Carlos Andres Perez', 'Sede A', 'Refrigerio', '3'),
  ('3456789012', 'Laura Valentina Gomez', 'Sede B', 'Almuerzo', '7'),
  ('4567890123', 'Sebastian Rodriguez', 'Sede B', 'Refrigerio', '9'),
  ('5678901234', 'Valentina Torres', 'Sede C', 'Almuerzo', '11'),
  ('6789012345', 'Andres Felipe Ramirez', 'Sede C', 'Refrigerio', '6'),
  ('7890123456', 'Sofia Martinez', 'Sede A', 'Almuerzo', '4'),
  ('8901234567', 'Juan Pablo Castro', 'Sede B', 'Refrigerio', '10'),
  ('9012345678', 'Mariana Suarez', 'Sede C', 'Almuerzo', '8'),
  ('0123456789', 'Daniel Vargas', 'Sede A', 'Refrigerio', '2')
) as datos(documento, nombre, sede, turno, grado)
where not exists (select 1 from beneficiarios);

-- Valoraciones de ejemplo: algunas estrellas ya puestas por los
-- estudiantes (solo si la tabla esta vacia)
insert into valoraciones (menu_id, puntos, documento)
select m.id, datos.puntos, datos.documento
from (values
  ('Arroz con pollo y ensalada', 5, '1234567890'),
  ('Arroz con pollo y ensalada', 4, '7890123456'),
  ('Sopa de verduras y pan', 3, '2345678901'),
  ('Pasta con salsa de tomate', 4, '5678901234'),
  ('Pescado con arroz y platano', 5, '3456789012'),
  ('Sancocho de gallina', 5, '9012345678'),
  ('Sancocho de gallina', 4, '4567890123')
) as datos(platillo, puntos, documento)
join menus m on m.platillo = datos.platillo and m.semana = 1 and m.jornada = 'Almuerzo'
where not exists (select 1 from valoraciones);
