-- ============================================================
-- PAE - Script completo de configuracion de la base de datos
-- Pegar todo esto en Supabase -> SQL Editor -> New query -> Run
-- Es SEGURO correrlo varias veces (no duplica datos).
-- ============================================================

-- 1. Tabla de menus: el catalogo semanal que se publica
create table if not exists menus (
  id bigint generated by default as identity primary key,
  dia text not null,
  platillo text not null,
  descripcion text,
  calorias integer,
  created_at timestamptz default now()
);

-- 2. Tabla de reservas: los estudiantes que confirman comida
create table if not exists reservas (
  id bigint generated by default as identity primary key,
  estudiante text not null,
  documento text not null,
  sede text not null,
  turno text not null,
  fecha date not null,
  created_at timestamptz default now()
);

-- 3. Tabla de contactos: mensajes del formulario de contacto
create table if not exists contactos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  correo text not null,
  mensaje text not null,
  created_at timestamptz default now()
);

-- ============================================================
-- 4. Politicas de acceso (RLS)
-- Sin estas politicas la app no puede leer/escribir.
-- RLS activo + politicas = la app publica lee menus y guarda
-- reservas/contactos.
-- ============================================================

alter table menus enable row level security;
create policy "menus_lectura_publica" on menus
  for select using (true);
create policy "menus_escritura_admin" on menus
  for insert with check (true);

alter table reservas enable row level security;
create policy "reservas_lectura" on reservas
  for select using (true);
create policy "reservas_creacion" on reservas
  for insert with check (true);
-- Permite limpiar datos de prueba desde la API (proyecto educativo)
create policy "reservas_borrado" on reservas
  for delete using (true);

alter table contactos enable row level security;
create policy "contactos_lectura" on contactos
  for select using (true);
create policy "contactos_creacion" on contactos
  for insert with check (true);

-- ============================================================
-- 5. Datos de ejemplo: menu de la semana
-- Se insertan SOLO si la tabla esta vacia (evita duplicados)
-- ============================================================
insert into menus (dia, platillo, descripcion, calorias)
select datos.dia, datos.platillo, datos.descripcion, datos.calorias
from (values
  ('Lunes', 'Arroz con pollo y ensalada', 'Arroz, pollo guisado, ensalada fresca y jugo natural.', 520),
  ('Martes', 'Sopa de verduras y pan', 'Sopa de verduras de temporada con pan integral.', 380),
  ('Miercoles', 'Pasta con salsa de tomate', 'Pasta integral con salsa casera de tomate y queso.', 460),
  ('Jueves', 'Pescado con arroz y platano', 'Pescado al horno, arroz blanco y platano asado.', 490),
  ('Viernes', 'Sancocho de gallina', 'Sancocho tradicional con yuca, platano y papa.', 550)
) as datos(dia, platillo, descripcion, calorias)
where not exists (select 1 from menus);
